# Generated by Django 4.1.7 on 2023-03-04 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_calculate',
            name='final_price',
            field=models.CharField(editable=False, max_length=10),
        ),
    ]
