# Generated by Django 4.1.7 on 2023-03-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_alter_price_calculate_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_calculate',
            name='Distance_Additional_Price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='price_calculate',
            name='Distance_Base_Price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='price_calculate',
            name='Distance_travel',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='price_calculate',
            name='Time_in_hours',
            field=models.IntegerField(),
        ),
    ]
