# Generated by Django 4.1.7 on 2023-03-04 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0003_alter_price_calculate_distance_additional_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price_calculate',
            name='final_price',
        ),
    ]
