# Generated by Django 4.1.7 on 2023-03-14 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0005_alter_price_calculate_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='price_calculate',
            name='user',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.IntegerField(null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='price.price_calculate')),
            ],
        ),
    ]
