# Generated by Django 4.1.7 on 2023-03-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0006_price_calculate_user_trips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_calculate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
